### ISSUE TITLE
Nested dynamic data sources / templates

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/support#19]
It would be great to have support for nested templates. I am sure that nested contract factories are rare but even if that's the case, there are use cases for dynamic data sources beyond contract factories.

**Comment by iherger** [comment]
As discussed on Discord:

Moving templates to the same level as standard data sources may be easier and allow for much more flexibility, since any data source could then potentially instantiate any other data source. A standard template is basically like a template source, except that the standard template has already been instantiated once. Instantiating standard data source several times should also be possible quite easily then.

**Comment by Jannis** [comment]
Yeah, let's flatten the templates and move them next to data sources:
```yaml
dataSources:
  - ...
  - ...
templates:
  - ...
  - ...
```

**Comment by leoyvens** [comment]
This is done.
