### ISSUE TITLE
Include network name in EthereumEvent

### ISSUE THREAD

**Issue by jjgonecrypto** [graphprotocol/support#37]
In order to reuse a mapping function for different networks in the one subgraph, I’d like the ethereum `network` name included as a property on `EthereumEvent’

**Comment by jjgonecrypto** [comment]
It will prevent me having to do wrapping functions a la: https://github.com/Synthetixio/synthetix-subgraph/blob/master/src/depot-mapping.ts#L27-L35 

@Jannis

**Comment by leoyvens** [comment]
The solution to this should consider that we also want access to other manifest fields, see #3, so putting it in `EthereumEvent` is not the best solution. We might want to start with a way to get data for the current data source, at least the network and address.

**Comment by Jannis** [comment]
@leoyvens Agreed. I think it would be worth making the data source available to mappings, at least its `name`, `source`, `abis` — the latter could come in a form that we can bind to them, like with `dataSource.abis.SomeContract.bind('...')`.

I see three options here:

1. We add a `dataSource` field to `EthereumEvent`, `EthereumCall` and `EthereumBlock` so that for all different handler types we can access the data source. What I don't like about that is that we mess with the Ethereum data structures. Also, since `EthereumEvent` includes an `EthereumBlock`, we'd include the data source multiple times.

2. We add a second parameter to handlers, something like a `Context` that has a `dataSource` field and that we can extend later. I'm not sure this is easily possible. In JS there is a lot of freedom with regards to passing (or not passing) in the right number of arguments, with WASM it's more strict.

3. We add a global `context` or `dataSource` or even `subgraph` module that allows to access the current data source (and in the `subgraph` module case, more data about the subgraph).

What do you guys think?

**Comment by leoyvens** [comment]
I think option 3 is the most straightforward. We have a `dataSource` namespace already, we can use that for `dataSource.network()` or `dataSource.address()`. I like how that reads, but maybe we should put it under a different namespace.
