### ISSUE TITLE
Feature request: checking content in more than one IPFS node

### ISSUE THREAD

**Issue by sistemico** [graphprotocol/support#41]
Loading unpinned files in the official IPFS nodes produce timeout in most cases. This is a limitation that prevents the development of some subgraphs in certain scenarios. For example, the SuperRare[1] subgraph is unable to process the artwork's metadata stored as JSON files in IPFS because pinning each descriptor file in advance is not possible. Although all the metadata is registered in the same IPFS node, they are pinned in a different node to the official one.

[1] https://github.com/protofire/superrare-subgraph/tree/ipfs-metadata

**Comment by Jannis** [comment]
Possible solution:

1. Make `graph-node` take more than one IPFS node via it's env vars / CLI args.
2. Create multiple IPFS clients in `graph-node` for each of the nodes.
3. Pass all of these to `LinkResolver` and implement resolution in `LinkResolver` so it fails over from one to the next when a file cannot be found, until either one node has the file or none of them have it.

**Comment by Jannis** [comment]
Some context: right now `graph-node` only talks to a single IPFS node. In fact, the entire hosted service relies on a single IPFS node. This currently requires all subgraphs to pin IPFS files they might need to index data from on our IPFS node (see https://thegraph.com/docs/define-a-subgraph#ipfs-pinning).

There are a number of public IPFS gateways out there that we should hit in turn, rather than just relying on our IPFS node. A good start would be to collect which gateways are out there.

Off the top of my head, I can think of:

* https://ipfs.infura.io:5001/ (e.g. https://ipfs.infura.io:5001/api/v0/version)
* https://ipfs.io/ (e.g. https://ipfs.io/api/v0/version)

**Comment by Jannis** [comment]
There's also CloudFlare but I'm not sure it works with IPFS clients out of the box: https://cloudflare-ipfs.com/ (e.g. https://cloudflare-ipfs.com/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/`)

**Comment by Jannis** [comment]
There's also https://ipfs.pixura.io/ipfs/, which may be needed for SuperRare. Like with CloudFlare, I'm not sure it's fully compatible with IPFS clients.

**Comment by That3Percent** [comment]
This has been implemented (for some time now, actually... sorry this should have been closed back then).

You can now supply multiple `-ipfs HOST:PORT` arguments on the command-line. When multiple IPFS nodes are available, the indexer will "race" the two nodes with a call to get the file stats (eg: how big the file is). Whichever node responds first is presumed to have the file and will be used to download it.
