### ISSUE TITLE
Comments with leading white space in graphql schema file cause deployment error

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/support#5]
Currently it's not possible to deploy a schema if it has a in-line comment with a leading white-space like so (e.g. when temporarily commenting out a part of the schema):

```
type Asset @entity {
  id: ID!
  decimals: Int!
  # symbol: String!
  # name: String!
}
```

This leads to a error during IPFS deployment: 
```
  Add file to IPFS build/schema.graphql
✖ Failed to upload subgraph to IPFS: Failed to upload file to IPFS: Unexpected token < in JSON at position 0
```

However, this works:

```
type Asset @entity {
  id: ID!
  decimals: Int!
  #symbol: String!
  #name: String!
}
```

Can be tested here: https://github.com/melonproject/melon-subgraph

**Comment by Jannis** [comment]
That's obscure! Going to look into it.

**Comment by fubhy** [comment]
Correction: It has nothing to do with the comments. Running `yarn deploy` again after a successful deploy without any changes in `schema.graphql` causes the error. It  seems to choke on a HTML response coming from IPFS (tries to JSON parse a 404/500 with a HTML response?!).

**Comment by fubhy** [comment]
So the reason why it worked afterwards is because the single character change in the schema (removing the white space) had it pass the IPFS deployment.

**Comment by Jannis** [comment]
Just to clarify: without any changes at all or just no changes in `schema.graphql`?

**Comment by Jannis** [comment]
Resolved the problem, it was an intermittent issue caused by proxing to `localhost` rather than `127.0.0.1` in our NGINX proxy for IPFS.

We're using proxies in different places, and if you have two co-located containers in a Kubernetes deployment, you have to be very careful not to proxy from one (nginx) to the other (ipfs / graph-node / whatever) using localhost. You have to use 127.0.0.1 for reasons that are beyond me. Otherwise you'll get random 502 gateway errors and those are... HTML, not JSON.

**Comment by rajatnishu25** [comment]
Failed to upload subgraph to IPFS: Failed to upload file to IPFS: connect ECONNREFUSED 127.0.0.1:5001

when i run yarn deploy-local cmd i am facing above issue

**Comment by tmac2yt** [comment]
> 
> 
> Failed to upload subgraph to IPFS: Failed to upload file to IPFS: connect ECONNREFUSED 127.0.0.1:5001
> 
> when i run yarn deploy-local cmd i am facing above issue

I facing the same issue,do you have solved?
