### ISSUE TITLE
[BUG] Emitted event between two contracts conflicts

### ISSUE THREAD

**Issue by ejwessel** [graphprotocol/support#57]
# Problem
I have two factory contracts (A, B) that both implement the same interface (C). The interface defines an event that both factory contracts emit. When attempting to index both contract A and B only one of the contracts is indexed for the emitted events.

# Steps to Reproduce
1. clone `airswap-protocols`
1. change to [AirSwap Draft PR #534]( https://github.com/airswap/airswap-protocols/pull/534) branch `subgraph_conflict`
1. from `airswap-protocols/'` run `yarn; yarn compile`
1. from a separate window start ganache `yarn ganache -h 0.0.0.0`
1. from a separate window `cd airswap-protocols/source/delegate; yarn test`
1. form a separate window start the local graph node provided by The Graph `docker-compose up`
1. from a separate window deploy local subgraph `yarn prepare:development && yarn codegen && yarn remove-local; yarn create-local; yarn deploy-local`
1. Search graph node logs to see either `handleCreateDelegate` or `handleCreateDelegateV2` handler called; only one is called.

# Other notes
* ganache is always started with a deterministic address, meaning created contracts are deterministic as well.
```
  "delegateFactory_address" : "0xA57B8a5584442B467b4689F1144D269d096A3daF",
  "delegateV2Factory_address" : "0x67B5656d60a809915323Bf2C40A8bEF15A152e3e",
```
* By changing the order of which tests runs first `Delegate.js` or `Delegate-V2.js` runs the result of which contract is indexed can be changed.
`yarn test test/Delegate-V2.js test/Delegate.js` results in `handleCreateDelegate` being called
`yarn test test/Delegate.js test/Delegate-V2.js` results in `handleCreateDelegateV2` being called.

**Comment by davekay100** [comment]
So we figured out the following:

- Ganache often will snapshot the blockchain, and completely revert the state
- This leads to misleading output by the graph node. Basically if multiple test files are run, it can lead to ganache resetting state multiple times. If you start the subgraph after the tests are done, it will only pick up the last run tests. If you start if before, it will freeze after the first run of tests. Basically if ganache snapshots and starts at a much earlier block, graph node doesn't know what to do, and just stops on the last block before the first snapshot. 

It would be a lot of work to fix this immediately, so we will open up a new issue, and try to do this in the future. We will close this issue for now, as I made the following recommendations for work arounds: 

- Test on rinkeby or even better, kovan because of its 1 second block time. (This might be too much extra work, because you have to write scripts, and not tests. but then at least they are persistent on a chain)
- Use ganache, but test each case in isolation (so only look at subgraph output one file at a time so snapshots aren't reverted
- Use ganache, but figure out a way to make snapshots not happen. Combining test files into one file might work here

**Comment by ejwessel** [comment]
> Truffle provides a clean room environment when running your test files. When running your tests against Ganache or Truffle Develop, Truffle will use advanced snapshotting features to ensure your test files don't share state with each other.

IIRC this is implemented over `contract`

Regarding the AirSwap Issue denoted above:
Because `Delegate.js` and `Delegate-V2.js` are two separate `contract` calls, the environment resets in between the two test files. This also explains why changing the order of which test runs first determines which contract is indexed. 

In short, the graph is working as expected, as it does not expect the underlying blockchain state to change. Development should focus on the individual components in isolation. If the individual components work as intended then it can be assumed with high confidence that they will not conflict over one another in production.

I was able to confirm this by moving the DelegateV2 tests into the DelegateV1 tests and running the entire suite. This prevents the chain from resetting and I was able to confirm that both handlers were called.
