### ISSUE TITLE
Is hosted service good for production

### ISSUE THREAD

**Issue by tharindukn** [graphprotocol/support#87]
**Do you want to request a feature or report a bug?**
get to know about the hosted service
**What is the current behavior?**
get to know about the hosted service
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
i am using a hosted service for avalanche sub graph. It is working fine. So when going live can we use the hosted service or do we need to host the system in our own servers

i saw some popular repos has use https://github.com/Uniswap/v3-subgraph for production ?
**What is the expected behavior?**
when going live what is the method to use

**Comment by schmidsi** [comment]
Hey @tharinduk90, yes the hosted-service is production ready. There are several subgraphs with very high traffic served by the hosted service. That said, please be aware that support for [Avalanche is still in beta](https://thegraph.com/docs/developer/create-subgraph-hosted#supported-networks) since it is a very new chain that does not have the same track record of stability and availability like Ethereum mainnet.

Feel free to reopen this issue if you have anymore questions.
