### ISSUE TITLE
Handler skipped due to execution failure 

### ISSUE THREAD

**Issue by tapmapp** [graphprotocol/support#88]
Hello, I am having an indexing error in the ropsten network with a super easy event.
It seems there is an error with my handler but i can not really find where cause is quite simple.
The contract is verified so you can take a look at the code if you wish

@schmidsi could you please show some light here please? :)

[https://ropsten.etherscan.io/address/0xa427974fa3819593c0530c473ee7ff60c4e8446b#code](https://ropsten.etherscan.io/address/0xa427974fa3819593c0530c473ee7ff60c4e8446b#code)

ID: QmZiby5mUNy5SWbbYuegybTL72CLY63XQQawj5giPF3Qki

event FaucetSent(address _from, uint256 _value);

```
type FaucetSentEvent @entity {
  id: ID!
  address: Bytes! # address
  amount: BigInt!
}
```

```
export function handleFaucetSent(event: FaucetSentEvent): void {
  let entity = new FaucetSentEvent(event.id);
  entity.id = event.id;
  entity.address = event.address;
  entity.amount = event.amount;
  entity.save();
}
```

<img width="1266" alt="Screenshot 2022-02-05 at 22 17 02" src="https://user-images.githubusercontent.com/7542950/152659351-a8bca3fb-4d10-4167-8688-8210146c7e6c.png">

**Comment by incrypto32** [comment]
@tapmapp in this code snippet `event: FaucetSentEvent` here you are using the entity name instead of the event `FaucetEvent`  

Replace it and you are good. Please refer to docs [here](https://thegraph.com/docs/en/developer/create-subgraph-hosted/#writing-mappings) And reach out to our discord if you need help.
